# Generated by Django 3.0.10 on 2020-10-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('link', models.TextField(max_length=100)),
                ('youtuber', models.TextField(max_length=20)),
                ('thumbnail', models.TextField(max_length=50)),
                ('key', models.TextField(max_length=30)),
            ],
        ),
    ]
